name: flutter_proj
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  geolocator: ^9.0.2
  permission_handler: ^11.0.1
  http: ^1.0.0
  animated_text_kit: ^4.2.2
  flutter_staggered_animations: ^1.1.1
  lottie: ^2.3.2
#  firebase_core: ^1.20.0
#  firebase_auth: ^3.5.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/nyatapola.jpg
    - assets/bhaktapur.png
    - assets/dattatreya.png
    - assets/changunarayan.png
    - assets/temple_icon.png
    - assets/user_profile.png